name: flutter_application_
description: "A new Flutter project."

# Prevents accidental publication to pub.dev
publish_to: 'none' 

# Application version information
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Dependencies for project functionality
  image_picker: ^0.8.5+3  # For image picking functionality
  cupertino_icons: ^1.0.8  # iOS-style icons
  intl: ^0.19.0  # For internationalization and date formatting
  location: ^7.0.1  # For location services
  carousel_slider: ^4.0.0  # For carousel feature in ReceiverPage
  http: ^0.14.0  # For making API calls to fetch dynamic data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Recommended lints for good coding practices

flutter:
  uses-material-design: true

  # Assets section for images and other static files
  assets:
    - assets/meat.jpeg

  # Fonts can be added here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
